using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using QPlayer.Utilities;
using System;
using System.Collections.Generic;
using System.Text;

namespace QPlayer.SourceGenerator;

public partial class ViewGeneratorGenerator
{
    /*
     This source generator generates the following code:

    public override UIElement Clone() => Clone(new Rectangle());

    public override UIElement Clone(UIElement target)
    {
        base.Clone(target);
        if (target is Rectangle t)
        {
            t.colour = colour;
            t.rounding = rounding;
        }
        return target;
    }
     
     */

    private static void Emit(SourceProductionContext context, ViewResult result)
    {
        if (result.Diagnostic != null)
            context.ReportDiagnostic(result.Diagnostic.ToDiagnostic());
        if (result.ViewClass is not ViewClass model)
            return;

        IndentedStringBuilder sb = new();

        Helpers.EmitFileHeader(sb, model.Namespace, model.EnableNullable, ["System", "QPlayer.ViewModels", "QPlayer.Views", "QPlayer.Utilities"]);

        /*sb.AppendLine("<auto-generated/>");
        sb.AppendLine("<!--                                                  -->");
        sb.AppendLine("<!-- This file is automatically generated by QPlayer. -->");
        sb.AppendLine("<!--                                                  -->");
        sb.AppendLine();*/

        sb.AppendLine($"public partial class {model.ClassName}View : ICueView");
        using (sb.EnterCurlyBracket())
        {
            sb.AppendLine($"public {model.ClassName}View()");
            using (sb.EnterCurlyBracket())
            {
                // sb.AppendLine("InitializeComponent();");
            }
            sb.AppendLine();
            sb.AppendLine("public static System.Windows.DataTemplate CreateDataTemplate()");
            using (sb.EnterCurlyBracket())
            {
                sb.AppendLine("var xaml = System.Windows.Markup.XamlReader.Parse(\"\"\"");

                using (sb.CreateXMLElement("DataTemplate",
                    //$"x:Class='{model.Namespace}.{model.ClassName}View'",
                    $"DataType='{{x:Type t:{model.ClassName}}}'",
                    "xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'",
                    "xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'",
                    "xmlns:mc='http://schemas.openxmlformats.org/markup-compatibility/2006'",
                    "xmlns:d='http://schemas.microsoft.com/expression/blend/2008'",
                    "xmlns:local='clr-namespace:QPlayer.Views;assembly=QPlayer'",
                    "xmlns:vm='clr-namespace:QPlayer.ViewModels;assembly=QPlayer'",
                    "xmlns:util='clr-namespace:QPlayer.Utilities;assembly=QPlayer'",
                    $"xmlns:t='clr-namespace:{model.Namespace};assembly={model.Assembly}'",
                    "mc:Ignorable='d'"
                    ))
                {
                    using (sb.CreateXMLElement("StackPanel", $"d:DataContext='{{d:DesignInstance Type=t:{model.ClassName}}}'", "d:DesignHeight='50' d:DesignWidth='250'"))
                    {
                        foreach (var prop in model.ViewProps)
                            CreateControl(sb, prop, model);
                    }
                }

                sb.AppendLine("\"\"\");");
                // sb.AppendLine("System.Diagnostics.Debugger.Break();");
                sb.AppendLine("return (System.Windows.DataTemplate)xaml;");
            }
        }

        var sourceText = SourceText.From(sb.ToString(), Encoding.UTF8);

        context.AddSource($"{model.ClassName}View.g.xaml", sourceText);

        //EmitStylableClass(context, result);
    }

    private static void CreateControl(IndentedStringBuilder sb, ViewProp prop, ViewClass model)
    {
        if (prop.HeadingTitle is string heading)
        {
            // <Label Content="XYZ" Background="{DynamicResource AREghZyBrush.Primary.3.Background.Static}" FontWeight="Bold" Margin="8,8,0,0"/>
            sb.AppendXMLElement("Label", $"Content=\"{heading}\"", 
                "Background=\"{DynamicResource AREghZyBrush.Primary.3.Background.Static}\"", 
                "FontWeight=\"Bold\"", "Margin=\"8,8,0,0\"");
        }

        using (sb.CreateXMLElement("DockPanel",
            prop.Tooltip != null ? [$"ToolTip=\"{prop.Tooltip}\""] : []))
        {
            if (prop.BtnCmd is string buttonCmd)
            {
                // Create a button (which has no label, hence nothing else to do)
                sb.AppendXMLElement("Button", $"Content=\"{prop.ViewLabel}\"", $"Command=\"{{Binding {buttonCmd}}}\"");
                return;
            }

            // Create a label
            sb.AppendXMLElement("Label", $"Content=\"{prop.ViewLabel}\"");

            string controlType = "local:TextField";
            using TemporaryList<string> attrs = new();

            // Spinner attrs
            bool isNumeric = true;
            switch (prop.PropType)
            {
                case nameof(Int32):
                case nameof(Int64):
                case "int":
                case "long":
                    attrs.Add("ShowSpinner='True'");
                    attrs.Add("SpinnerType='Int'");
                    break;
                case nameof(Single):
                case nameof(Double):
                case "float":
                case "double":
                    attrs.Add("ShowSpinner='True'");
                    attrs.Add("SpinnerType='Double'");
                    break;
                case nameof(TimeSpan):
                    attrs.Add("ShowSpinner='True'");
                    attrs.Add("SpinnerType='TimeSpan'");
                    break;
                default:
                    isNumeric = false;
                    break;
            }

            // Set the control type
            if (prop.IsKnob)
                controlType = "local:Knob";
            else if (prop.IsSlider)
                controlType = "Slider";
            else if (prop.EnumValues != null)
                controlType = "ComboBox";
            else if (prop.PropType == nameof(Boolean))
                controlType = "CheckBox";

            // Apply range parameters
            if (prop.Range is Range range && isNumeric)
            {
                attrs.Add($"ClampValue='{((prop.Range?.Clamp ?? false) ? "True" : "False")}'");
                if (range.Min != double.MinValue)
                    attrs.Add($"MinValue='{range.Min}'");
                if (range.Max != double.MaxValue)
                    attrs.Add($"MaxValue='{range.Max}'");
                if (range.Rate != 0)
                    attrs.Add($"SpinRate='{range.Rate}'");
            }

            // Bind the value
            if (controlType == "local:TextField")
            {
                attrs.Add($"Text='{{Binding {prop.PropName}, UpdateSourceTrigger=Default}}'");
            }
            else if (prop.EnumValues != null)
            {
                // <ComboBox SelectedItem="{Binding LoopMode}" ItemsSource="{Binding LoopModeVals}" DockPanel.Dock="Right" Margin="8,2,2,2"/>
                attrs.Add($"SelectedItem='{{Binding {prop.PropName}}}'");
                attrs.Add($"ItemsSource='{{Binding {prop.PropType}Vals}}'");
            }
            else
            {
                attrs.Add($"Value='{{Binding {prop.PropName}, UpdateSourceTrigger=Default}}'");
            }

            attrs.Add("Margin='8,2,2,2'");

            if (prop.ReadOnly) // TODO: We also need to set the binding to OneWay
                attrs.Add("IsEnabled='False'");

            if (prop.FilePickerCmd is string fpCmd)
            {
                // <Button Content="..." Width="30" Command="{Binding OpenMediaFileCommand}" HorizontalAlignment="Right" DockPanel.Dock="Right"/>
                sb.AppendXMLElement("Button", ["Content='...'", "Width='30'", "HorizontalAlignment='Right'", "DockPanel.Dock='Right'",
                    $"Command='{{Binding {fpCmd}}}'"]);
            }
            else
            {
                attrs.Add("DockPanel.Dock='Right'");
            }

            sb.AppendXMLElement(controlType, attrs.AsSpan());
        }
    }
}
